package com.capgemini.healthcaresystem.dao;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;

import com.fasterxml.jackson.annotation.JsonFormat;

@Entity
	public class Appointment {
		/**
		 * id of project , primary key and autogenerated
		 */
		@Id
		@GeneratedValue(strategy = GenerationType.IDENTITY)
		private int id;
		/**
		 * date at which appointment is taken
		 */
		@JsonFormat(pattern="yyyy-MM-dd")
		private LocalDate appointmentDate=LocalDate.now();
		/**
		 * approval status from admin
		 */
		private String approvalStatus;
		/**
		 * selection of diagnostic test, one to many
		 */
		
		@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER,mappedBy = "appointment")
		//@JoinColumn(name = "tesresultid", updatable = false, nullable = false)
		//private TestResult testResult;
		private List<TestResult> testresults =  new ArrayList<>();
		
		@OneToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL, mappedBy = "appointment")
		private DiagnosticCenter diagnosticCenter;
		
		@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, mappedBy = "appointment")
		
		private Set<DiagnosticTest> tests=new HashSet<>();
		public Appointment() {
			super();
		}
		
		public List<TestResult> getTestresults() {
			return testresults;
		}
		public void setTestresults(List<TestResult> testresults) {
			this.testresults = testresults;
		}
		
		public int getId() {
			return id;
		}
		public void setId(int id) {
			this.id = id;
		}
		
		public LocalDate getAppointmentDate() {
			return appointmentDate;
		}
		public void setAppointmentDate(LocalDate appointmentDate) {
			this.appointmentDate = appointmentDate;
		}
		public String getApprovalStatus() {
			return approvalStatus;
		}
		public void setApprovalStatus(String approvalStatus) {
			this.approvalStatus = approvalStatus;
		}
		public Set<DiagnosticTest> getTests() {
			return tests;
		}
		public void setTests(Set<DiagnosticTest> tests) {
			this.tests = tests;
		}
		public DiagnosticCenter getDiagnosticCenter() {
			return diagnosticCenter;
		}
		public void setDiagnosticCenter(DiagnosticCenter diagnosticCenter) {
			this.diagnosticCenter = diagnosticCenter;
		}
		
	}
